apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-dep
  labels:
      app: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: app
        image: ##DOCKER_PREFIX##/streamlit-app
        ports:
        - containerPort: 8080
          name: app-port
        env:       
        - name: OCI_CLI_AUTH
          value: "instance_principal"
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: streamlit-db-secret
              key: db_url      
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: streamlit-db-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: streamlit-db-secret
              key: db_password
#        - name: POD_IP
#          valueFrom:
#            fieldRef:
#              fieldPath: status.podIP
      imagePullSecrets:
      - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  selector:
    app: streamlit-app
  ports:
  - name: http-service-port
    protocol: TCP
    port: 80
    targetPort: app-port
